services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - VPN_TYPE=wireguard
      - VPN_SERVICE_PROVIDER=custom
      - WIREGUARD_PRIVATE_KEY=Example
      - WIREGUARD_PUBLIC_KEY=Example
      - WIREGUARD_PRESHARED_KEY=Example
      - WIREGUARD_ADDRESSES=Example
      - WIREGUARD_ENDPOINT_IP=Example
      - WIREGUARD_ENDPOINT_PORT=Example
      - WIREGUARD_ALLOWED_IPS=Example
      - FIREWALL=on
      - FIREWALL_INPUT_PORTS=8080
      - DNS=1.1.1.1,1.0.0.1
      - DOT=off
      - TZ=America/New_York
      - HEALTH_TARGET_ADDRESS=1.1.1.1:53
      - HEALTH_TIMEOUT=10s
      - HEALTH_VPN_TIMEOUT=30s
    volumes:
      - /mnt/Drive1/Docakge/config/gluetun:/gluetun
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8080:8080
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: service:gluetun
    depends_on:
      - gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - WEBUI_PORT=8080
    volumes:
      - /mnt/Drive1/Docakge/config/qbittorrent:/config
      - /mnt/Drive1/QBittorrent/Downloads:/downloads
    restart: unless-stopped
networks: {}