services:
  ombi:
    image: lscr.io/linuxserver/ombi:latest
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /mnt/Drive1/Ombi/config:/config
    ports:
      - 3579:3579
    restart: unless-stopped