services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /mnt/Drive1/Sonarr/config:/config
      - /mnt/Drive1/Plex/TV:/tv
      - /mnt/Drive1/QBittorrent/Downloads:/downloads
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    ports:
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /mnt/Drive1/Radarr/config:/config
      - /mnt/Drive1/Plex/Movies:/movies
      - /mnt/Drive1/QBittorrent/Downloads:/downloads
    restart: unless-stopped