services:
  wordpress:
    image: wordpress:latest
    restart: unless-stopped
    ports:
      - 8081:80
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - /mnt/Drive1/WordPressStack/wordpress/wordpress:/var/www/html
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:10.5
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - /mnt/Drive1/WordPressStack/mariadb:/var/lib/mysql
networks: {}