version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: host  
    restart: unless-stopped
    environment:
      TZ: "America/New_York"  
      WEBPASSWORD: "example"  
    volumes:
      - pihole_etc:/etc/pihole
      - dnsmasq_etc:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN

volumes:
  pihole_etc:
  dnsmasq_etc: